services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ./home/Desktop/data:/var/lib/mysql
    networks:
      - app_network
  backend:
    build:
      context: https://github.com/etec-integration-project/2025-backend-FacuLlamas.git
      dockerfile: Dockerfile
    restart: always
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app_network

networks:
  app_network:
